---
- hosts: linuxservers
  become: yes

  tasks:
  - name: Create file
    file:
      path: /root/testfile.txt
      state: touch

- name: Add line in file
  lineinfile:
    path: /root/testfiles.txt
    line: Ansible was here...